export const AUTH_ROUTE = '/auth'
export const SIGNUP_ROUTE = '/signup'
export const LOGIN_ROUTE = '/login'
export const REFRESH_TOKEN_ROUTE = '/refresh-token'
export const LOGOUT_ROUTE = '/logout'
export const FORGOT_PASSWORD_ROUTE = '/forgot-password'
export const RESET_PASSWORD_ROUTE = '/reset-password'